UI = {
    'en': {
        'brand_tagline': 'Evidence over noise.',
        'home': 'Home', 'explore': 'Explore', 'leaderboard': 'Leaderboard', 'new_claim': 'New claim',
        'login': 'Log in', 'logout': 'Log out', 'register': 'Create account', 'profile': 'Profile',
        'language': 'العربية', 'feed_title': 'Claims worth examining',
        'feed_subtitle': 'Follow evidence, not engagement.', 'all_topics': 'All topics', 'filter': 'Filter',
        'no_claims': 'No claims here yet.', 'start_claim': 'Publish the first claim',
        'evidence': 'Evidence', 'positions': 'Positions', 'supports': 'Supports', 'contradicts': 'Contradicts',
        'context': 'Context', 'true': 'True', 'false': 'False', 'unsure': 'Unsure', 'confidence': 'Confidence',
        'take_position': 'Take a position', 'save_position': 'Save position', 'add_evidence': 'Add evidence',
        'source': 'Source', 'source_title': 'Source title', 'note': 'Note', 'publish': 'Publish', 'cancel': 'Cancel',
        'claim_text': 'What are you claiming?', 'topic': 'Topic', 'type': 'Type', 'resolution_date': 'Resolution date',
        'fact': 'Factual claim', 'prediction': 'Prediction', 'opinion': 'Opinion',
        'open': 'Open', 'verified': 'Verified', 'disputed': 'Disputed', 'unresolved': 'Unresolved',
        'by': 'by', 'credibility': 'Credibility', 'resolved_predictions': 'Resolved predictions',
        'correct_predictions': 'Correct', 'evidence_reputation': 'Evidence reputation', 'recent_claims': 'Recent claims',
        'follow': 'Follow', 'unfollow': 'Unfollow', 'followers': 'Followers', 'following': 'Following',
        'username': 'Username', 'password': 'Password', 'password_confirm': 'Confirm password',
        'already_account': 'Already have an account?', 'new_here': 'New to Proof?', 'sign_in': 'Sign in',
        'create_account': 'Create account', 'community_position': 'Community position', 'useful': 'Useful',
        'not_useful': 'Not useful', 'score': 'Score', 'rank': 'Rank', 'member': 'Member', 'topic_scores': 'Topic credibility',
        'prediction_due': 'Resolves', 'published': 'Published', 'search_placeholder': 'Filter claims by topic',
        'global_feed': 'Global', 'following_feed': 'Following', 'discovery_note': 'Your following feed appears after you follow someone.',
        'claim_detail': 'Claim', 'back_feed': 'Back to feed', 'empty_evidence': 'No evidence submitted yet.',
        'stance': 'Stance', 'source_url': 'Source URL', 'published_at': 'Source publication date',
        'submit_evidence': 'Submit evidence', 'your_position': 'Your position', 'view_profile': 'View profile', 'ranked_feed':'Evidence-ranked feed', 'ranking_note':'Ranking rewards evidence, credibility, useful disagreement, freshness, and diversity — not raw popularity.', 'why_shown':'Why you are seeing this', 'source_quality':'Source quality', 'evidence_summary':'Evidence balance', 'evidence_note':'What this evidence says', 'source_details':'Source details', 'provenance_quality':'Source provenance', 'provenance_note':'Measures source metadata quality, not whether the claim is true.', 'open_source':'Open source', 'publisher':'Publisher', 'domain':'Domain', 'source_date':'Published', 'submitted_by':'Submitted by',
    },
    'ar': {
        'brand_tagline': 'الدليل قبل الضوضاء.',
        'home': 'الرئيسية', 'explore': 'استكشاف', 'leaderboard': 'الأكثر مصداقية', 'new_claim': 'ادعاء جديد',
        'login': 'تسجيل الدخول', 'logout': 'تسجيل الخروج', 'register': 'إنشاء حساب', 'profile': 'الملف الشخصي',
        'language': 'English', 'feed_title': 'ادعاءات تستحق الفحص',
        'feed_subtitle': 'اتبع الدليل، لا التفاعل.', 'all_topics': 'كل الموضوعات', 'filter': 'تصفية',
        'no_claims': 'لا توجد ادعاءات هنا بعد.', 'start_claim': 'انشر أول ادعاء',
        'evidence': 'الأدلة', 'positions': 'المواقف', 'supports': 'يؤيد', 'contradicts': 'يناقض',
        'context': 'سياق', 'true': 'صحيح', 'false': 'خطأ', 'unsure': 'غير متأكد', 'confidence': 'درجة الثقة',
        'take_position': 'حدد موقفك', 'save_position': 'حفظ الموقف', 'add_evidence': 'إضافة دليل',
        'source': 'المصدر', 'source_title': 'عنوان المصدر', 'note': 'ملاحظة', 'publish': 'نشر', 'cancel': 'إلغاء',
        'claim_text': 'ما الادعاء الذي تريد طرحه؟', 'topic': 'الموضوع', 'type': 'النوع', 'resolution_date': 'موعد الحسم',
        'fact': 'ادعاء واقعي', 'prediction': 'توقع', 'opinion': 'رأي',
        'open': 'مفتوح', 'verified': 'متحقق', 'disputed': 'محل نزاع', 'unresolved': 'غير محسوم',
        'by': 'بواسطة', 'credibility': 'المصداقية', 'resolved_predictions': 'توقعات محسومة',
        'correct_predictions': 'صحيحة', 'evidence_reputation': 'سمعة الأدلة', 'recent_claims': 'أحدث الادعاءات',
        'follow': 'متابعة', 'unfollow': 'إلغاء المتابعة', 'followers': 'متابعون', 'following': 'يتابع',
        'username': 'اسم المستخدم', 'password': 'كلمة المرور', 'password_confirm': 'تأكيد كلمة المرور',
        'already_account': 'لديك حساب بالفعل؟', 'new_here': 'جديد على Proof؟', 'sign_in': 'دخول',
        'create_account': 'إنشاء الحساب', 'community_position': 'موقف المجتمع', 'useful': 'مفيد',
        'not_useful': 'غير مفيد', 'score': 'الدرجة', 'rank': 'الترتيب', 'member': 'العضو', 'topic_scores': 'المصداقية حسب الموضوع',
        'prediction_due': 'موعد الحسم', 'published': 'نُشر', 'search_placeholder': 'صفِّ الادعاءات حسب الموضوع',
        'global_feed': 'عام', 'following_feed': 'المتابَعون', 'discovery_note': 'سيظهر موجز المتابَعين بعد متابعة أي شخص.',
        'claim_detail': 'الادعاء', 'back_feed': 'العودة للموجز', 'empty_evidence': 'لم تتم إضافة أدلة بعد.',
        'stance': 'الموقف من الادعاء', 'source_url': 'رابط المصدر', 'published_at': 'تاريخ نشر المصدر',
        'submit_evidence': 'إرسال الدليل', 'your_position': 'موقفك', 'view_profile': 'عرض الملف الشخصي', 'ranked_feed':'موجز مرتب بالدليل', 'ranking_note':'الترتيب يكافئ الأدلة والمصداقية والخلاف المفيد والحداثة والتنوع — وليس الشعبية الخام.', 'why_shown':'لماذا ظهر لك', 'source_quality':'جودة المصدر', 'evidence_summary':'توازن الأدلة', 'evidence_note':'ماذا يقول هذا الدليل', 'source_details':'بيانات المصدر', 'provenance_quality':'جودة توثيق المصدر', 'provenance_note':'تقيس اكتمال بيانات المصدر، ولا تعني أن الادعاء صحيح.', 'open_source':'فتح المصدر', 'publisher':'الناشر', 'domain':'النطاق', 'source_date':'تاريخ النشر', 'submitted_by':'أضافه',
    },
}

def language_for(request):
    lang = request.session.get('ui_lang', 'ar')
    return lang if lang in UI else 'ar'
